# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pw_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(431, 309)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(20, 10, 256, 271))
        self.listView.setObjectName("listView")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBar.setGeometry(QtCore.QRect(260, 10, 16, 271))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.new_btn = QtWidgets.QPushButton(self.centralwidget)
        self.new_btn.setGeometry(QtCore.QRect(320, 200, 75, 23))
        self.new_btn.setObjectName("new_btn")
        self.del_btn = QtWidgets.QPushButton(self.centralwidget)
        self.del_btn.setGeometry(QtCore.QRect(320, 260, 75, 23))
        self.del_btn.setObjectName("del_btn")
        self.save_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_btn.setGeometry(QtCore.QRect(320, 230, 75, 23))
        self.save_btn.setObjectName("save_btn")
        self.site = QtWidgets.QLabel(self.centralwidget)
        self.site.setGeometry(QtCore.QRect(290, 10, 47, 12))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.site.setFont(font)
        self.site.setObjectName("site")
        self.user_name = QtWidgets.QLabel(self.centralwidget)
        self.user_name.setGeometry(QtCore.QRect(290, 60, 61, 16))
        self.user_name.setObjectName("user_name")
        self.site_input = QtWidgets.QLineEdit(self.centralwidget)
        self.site_input.setGeometry(QtCore.QRect(290, 30, 131, 20))
        self.site_input.setText("")
        self.site_input.setObjectName("site_input")
        self.user_name_input = QtWidgets.QLineEdit(self.centralwidget)
        self.user_name_input.setGeometry(QtCore.QRect(290, 80, 131, 20))
        self.user_name_input.setObjectName("user_name_input")
        self.pw_input = QtWidgets.QLineEdit(self.centralwidget)
        self.pw_input.setGeometry(QtCore.QRect(290, 130, 131, 20))
        self.pw_input.setObjectName("pw_input")
        self.password = QtWidgets.QLabel(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(290, 110, 61, 16))
        self.password.setObjectName("password")
        self.generate = QtWidgets.QPushButton(self.centralwidget)
        self.generate.setGeometry(QtCore.QRect(320, 170, 75, 23))
        self.generate.setObjectName("generate")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.statusbar.setFont(font)
        self.statusbar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.statusbar.setStyleSheet("color: rgb(255, 0, 0);")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Password Control"))
        self.new_btn.setText(_translate("MainWindow", "New"))
        self.del_btn.setText(_translate("MainWindow", "Delete"))
        self.save_btn.setText(_translate("MainWindow", "Save"))
        self.site.setText(_translate("MainWindow", "Site"))
        self.user_name.setText(_translate("MainWindow", "User name"))
        self.password.setText(_translate("MainWindow", "Password"))
        self.generate.setText(_translate("MainWindow", "Generate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
